# Generated by Django 2.2.1 on 2019-11-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working_logs', '0002_auto_20191021_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opinion',
            options={'verbose_name_plural': 'Opinions'},
        ),
        migrations.AlterField(
            model_name='opinion',
            name='date_added',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_added',
            field=models.DateField(),
        ),
    ]
