# Generated by Django 2.2.1 on 2019-11-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working_logs', '0003_auto_20191105_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='date_added',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
