# Generated by Django 2.2.1 on 2019-11-08 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('working_logs', '0004_auto_20191105_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='time_added',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='time_added',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opinion',
            name='date_added',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_added',
            field=models.DateField(),
        ),
    ]
