# Generated by Django 2.2.5 on 2019-11-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working_logs', '0006_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img',
            name='img',
        ),
        migrations.AddField(
            model_name='img',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
