# Generated by Django 2.2.5 on 2019-11-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working_logs', '0007_auto_20191120_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img_url',
            field=models.FileField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
