# Generated by Django 2.2.1 on 2020-06-23 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('working_logs', '0009_thumb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('can_approve_or_reject_project', 'Can approve or reject project'),)},
        ),
        migrations.DeleteModel(
            name='Thumb',
        ),
    ]
